- name: Install ARK instances. This will take some time.
  shell: |
    if [ ! -f "/home/{{ ark_user }}/arkservers/{{ item.name | lower }}/version.txt" ]; then
      arkmanager install @{{ item.name | replace('_P','') | lower }};
    else
      echo "ARK instance is already installed!"
      exit 0
    fi
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Install ARK mods. This will take some time.
  shell: |
    if [ ! -f "/home/{{ ark_user }}/arkservers/{{ item.name | lower }}/version.txt" ]; then
      arkmanager installmods @{{ item.name | replace('_P','') | lower }};
    else
      echo "ARK mods have already been deployed!"
      exit 0
    fi
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Deploy ARK customized Engine.ini file.
  template:
    src: ./roles/ark-deploy/templates/Engine.ini.j2
    dest: "/home/{{ ark_user }}/arkservers/{{ item.name | lower }}/ShooterGame/Saved/Config/LinuxServer/Engine.ini"
    mode: 0644
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Increase Crystal Isles spawn rate.
  command: "sed -i 's/DinoCountMultiplier=1.0/DinoCountMultiplier={{ ci_spawn_multiplier }}/' /home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini"
  with_items: "{{ ark_server_maps }}"
  when:
    - item.enabled == true
    - item.name == "CrystalIsles"
