- name: Include secret variables.
  include_vars: ./roles/ark-deploy/vars/secrets.yml

- name: Deploy ARK instance configurations.
  template:
    src: ./roles/ark-deploy/templates/ark_instance.cfg.j2
    dest: "/etc/arkmanager/instances/{{ item.name | replace('_P','') | lower }}.cfg"
    mode: 0644
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Deploy ARK customized Game.ini file.
  template:
    src: ./roles/ark-deploy/templates/Game.ini.j2
    dest: /etc/arkmanager/config.Game.ini
    mode: 0644

- name: Deploy ARK customized GameUserSettings.ini file.
  template:
    src: ./roles/ark-deploy/templates/GameUserSettings.ini.j2
    dest: "/etc/arkmanager/config.{{ item.name | lower }}.GameUserSettings.ini"
    mode: 0644
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Make ARK Saved directory.
  file:
    path: "/home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved"
    state: directory
    owner: "{{ ark_user }}"
    group: "{{ ark_group }}"
    mode: 0755
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Make ARK Config directory.
  file:
    path: "/home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved/Config"
    state: directory
    owner: "{{ ark_user }}"
    group: "{{ ark_group }}"
    mode: 0755
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Make ARK LinuxServer directory.
  file:
    path: "/home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved/Config/LinuxServer"
    state: directory
    owner: "{{ ark_user }}"
    group: "{{ ark_group }}"
    mode: 0755
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Deploy ARK customized Engine.ini file.
  template:
    src: ./roles/ark-deploy/templates/Engine.ini.j2
    dest: "/home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved/Config/LinuxServer/Engine.ini"
    mode: 0644
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Increase Crystal Isles spawn rate.
  command: "sed -i 's/DinoCountMultiplier=1.0/DinoCountMultiplier={{ ci_spawn_multiplier }}/' /home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini"
  with_items: "{{ ark_server_maps }}"
  when:
    - item.enabled == true
    - item.name == "CrystalIsles"
