- name: Deploy update check cronjobs.
  cron:
    name: arkupdate
    job: "arkmanager update @{{ item.name | replace('_P','') | lower }} --safe --warn --saveworld --backup --update-mods"
    user: root
    hour: 10
    minute: 30
    state: present
  with_items: "{{ ark_server_maps }}"

- name: Deploy update check cronjobs.
  cron:
    name: arkupdate
    job: "arkmanager backup @{{ item.name | replace('_P','') | lower }}"
    user: root
    minute: 0
    state: present
  with_items: "{{ ark_server_maps }}"
