- name: Copy restart bash script.
  copy:
    src: "{{ role_path }}/files/restart.sh"
    dest: "/home/{{ ark_user }}/arkservers/restart.sh"
    mode: u+x
    owner: "{{ ark_user }}"
    group: "{{ ark_group }}"

- name: Deploy backup cronjobs.
  cron:
    name: "arkbackup-{{ item.name | replace('_P','') | lower }}"
    job: "arkmanager backup @{{ item.name | replace('_P','') | lower }}"
    user: root
    hour: 9
    minute: 30
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true

- name: Deploy nightly restart cronjob.
  cron:
    name: "arkrestart-{{ item.name | replace('_P','') | lower }}"
    job: "arkmanager restart @{{ item.name | replace('_P','') | lower }} --safe --saveworld --backup --warn &> /tmp/{{ item.name | replace('_P','') | lower }}-restart_$(date +%Y%m%d).log"
    user: root
    hour: 10
    minute: 0
  with_items: "{{ ark_server_maps }}"
  when: item.enabled == true
