- name: Deploy daily backup cronjob.
  cron:
    name: "arkbackup-all"
    job: "sudo arkmanager backup @all &> /tmp/arkmanager-restart_$(date '+%Y%m%d').log"
    user: ubuntu
    hour: 22
    minute: 0
    cron_file: /etc/crontab

- name: Deploy nightly restart cronjob.
  cron:
    name: "arkrestart-all"
    job: "sudo arkmanager restart @all --safe --saveworld --backup --warn &> /tmp/arkmanager-restart_$(date '+%Y%m%d').log"
    user: ubuntu
    hour: 10
    minute: 0
    cron_file: /etc/crontab
