- name: Check if ARK installs have already been done.
  stat:
    path: /home/{{ ark_user }}/arkservers/instances_installed.cfg
  register: ark_instances_installed

- name: Install ARK instances. This will take some time.
  shell: |
    if [[ `stat /home/{{ ark_user }}/arkservers/{{ item.name | replace('_P','') | lower }}/version.txt` -ne 0 ]]; then
      arkmanager install @{{ item.name | replace('_P','') | lower }};
    else
      echo "ARK instance is already installed!"
      exit 0
    fi
  with_items: "{{ ark_server_maps }}"

- name: Install ARK mods. This will take some time.
  command: "arkmanager installmods @{{ item.name | replace('_P','') | lower }}"
  with_items: "{{ ark_server_maps }}"
  when: not ark_instances_installed.stat.exists

- name: Create ARK instance installed flag.
  template:
    src: ./roles/ark-deploy/templates/instances_installed.cfg.j2
    dest: /home/{{ ark_user }}/arkservers/instances_installed.cfg
    owner: "{{ ark_user }}"
    group: "{{ ark_group }}"
    mode: 0644
